import type { Alert, AlertHistoryEntry } from '@/types/alert'

function isoHoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString()
}

export const ALERTS: Alert[] = [
  {
    id: 'a-001',
    sensorId: 's-001',
    zone: 'Maipú Centro',
    address: 'Av. Pajaritos 1234',
    latitude: -33.5167,
    longitude: -70.7575,
    nivelDb: 82,
    detectedAt: isoHoursAgo(2),
    status: 'activa',
    citizenName: 'Carla Soto',
    description: 'Música a alto volumen desde local en la esquina, sostenida desde las 22h.',
  },
  {
    id: 'a-002',
    sensorId: 's-002',
    zone: 'Plaza Maipú',
    address: 'Plaza de Maipú s/n',
    latitude: -33.5104,
    longitude: -70.7569,
    nivelDb: 76,
    detectedAt: isoHoursAgo(5),
    status: 'atendida',
    citizenName: 'Jorge Pérez',
    description: 'Evento masivo sin permisos visibles en plaza central.',
  },
  {
    id: 'a-003',
    sensorId: 's-007',
    zone: 'Rinconada',
    address: 'Calle Los Maitenes 567',
    latitude: -33.5512,
    longitude: -70.7405,
    nivelDb: 71,
    detectedAt: isoHoursAgo(8),
    status: 'cerrada',
    citizenName: 'María Rojas',
    description: 'Trabajos de construcción fuera de horario permitido.',
  },
  {
    id: 'a-004',
    sensorId: 's-008',
    zone: 'Industrial Maipú',
    address: 'Camino a Lonquén km 2',
    latitude: -33.4882,
    longitude: -70.7715,
    nivelDb: 89,
    detectedAt: isoHoursAgo(1),
    status: 'activa',
    citizenName: 'Daniel Aguirre',
    description: 'Maquinaria pesada operando de noche junto a zona habitacional.',
  },
  {
    id: 'a-005',
    sensorId: 's-009',
    zone: 'Longitudinal',
    address: 'Longitudinal 9087',
    latitude: -33.5150,
    longitude: -70.7892,
    nivelDb: 68,
    detectedAt: isoHoursAgo(12),
    status: 'atendida',
    citizenName: 'Patricia Vega',
    description: 'Tránsito vehicular intenso con bocinas excesivas.',
  },
  {
    id: 'a-006',
    sensorId: 's-004',
    zone: 'El Bosque',
    address: 'Av. El Bosque 3210',
    latitude: -33.5298,
    longitude: -70.7641,
    nivelDb: 78,
    detectedAt: isoHoursAgo(3),
    status: 'activa',
    citizenName: 'Sebastián Lara',
    description: 'Fiesta familiar excediendo niveles permitidos en horario nocturno.',
  },
  {
    id: 'a-007',
    sensorId: 's-010',
    zone: 'San Luis',
    address: 'Pasaje San Luis 45',
    latitude: -33.5365,
    longitude: -70.7510,
    nivelDb: 73,
    detectedAt: isoHoursAgo(20),
    status: 'cerrada',
    citizenName: 'Ana González',
    description: 'Vehículo con sistema de sonido alterado.',
  },
  {
    id: 'a-008',
    sensorId: 's-006',
    zone: 'Cerrillos límite',
    address: 'Cerrillos 22',
    latitude: -33.4998,
    longitude: -70.7320,
    nivelDb: 80,
    detectedAt: isoHoursAgo(0.5),
    status: 'activa',
    citizenName: 'Roberto Núñez',
    description: 'Local nocturno con música muy alta.',
  },
]

export const ALERT_HISTORY: AlertHistoryEntry[] = [
  {
    id: 'h-001',
    alertId: 'a-002',
    funcionarioId: 'f-001',
    funcionarioName: 'Pedro Funcionario',
    previousStatus: 'activa',
    newStatus: 'atendida',
    comment: 'Inspector enviado a verificar. Requiere visita en terreno.',
    changedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    isReversion: false,
  },
  {
    id: 'h-002',
    alertId: 'a-003',
    funcionarioId: 'f-001',
    funcionarioName: 'Pedro Funcionario',
    previousStatus: 'activa',
    newStatus: 'atendida',
    comment: 'Visita programada con la empresa constructora.',
    changedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    isReversion: false,
  },
  {
    id: 'h-003',
    alertId: 'a-003',
    funcionarioId: 'f-001',
    funcionarioName: 'Pedro Funcionario',
    previousStatus: 'atendida',
    newStatus: 'cerrada',
    comment: 'Notificación entregada y obra suspendida en horario nocturno.',
    changedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    isReversion: false,
  },
]
